### PR TITLE
feat: add VersionBump(Strategy) to ConventionalCommit message instances

### PR DESCRIPTION
**Pull request by juckerf**
Adds methods to determine if a given commit is a fix or feature commit and one method to determine which version bump a given commit mandates

### CODE REVIEW

**Review by leodido — COMMENTED** [review]
Hello! Thank you for sending this :)

It's definitely a good idea. An addition I'd like to include. 💯 

Anyways, to make it ready it needs some modifications.

The parser supports a few sets of types 

https://github.com/leodido/go-conventionalcommits/blob/4985e12c16060a56c8d923ce91a1ec60a5355617/parser/machine.go.rl#L225-L231

 and we don't retain (at the moment) which set the parser was configured for (with the `WithTypes(...)` option setter) at instantiation.

Notice that also "free form" is supported...

That information (the set in use) is only available in the parser currently and not in the resulting object:

https://github.com/leodido/go-conventionalcommits/blob/4985e12c16060a56c8d923ce91a1ec60a5355617/parser/machine.go.rl#L399

I'll think more on what's the best way to solve/design this.

For sure we'd need to create a mapping between the types of a set, and their meaning. 
Namely, minor or patch change.

For example, assuming `falco_types` are in use:

- minor change: feat, new (bumps 0.Y.0)
- patch change: all the other types (bumps 0.0.Z)

IMHO there are 2 possible paths:

1. detect the kind of change (minor change, patch change) when the parsing has been completed and store it in the output message (adding fields to their struct)

2. store (with an integer index - 0, 1, etc.) the type set configuration in the output message and handle the matching type/kind of change at an upper layer 

I'd prefer 2, which is also very similar to what you have done (ty!) to untie it from the parsing (and do not interfere with the parsing performances).

Also doing it at a higher level gives way more flexibility to the user to be able to define their matchings (which turns to be very useful in case the `free_form` is in use.

Lemme know if it's all clear and what do you think about it!

**Comment by juckerf** [comment]
Thanks for your review and the valuable input.
I'd also prefer the solution which stores the type set configuration in the output message. I'll adapt my MR accordingly.

And to sort some things out:
* the conventional commit specification is not explicit about bumping anything else than `patch`, `feat` or `breaking changes`. Therefore I implemented other types as an "unknown" bump for now. Although many other tools in the field do bump the patch version on any type other than `feat` or `breaking change`. Which way do you prefer for this tool?
* in the `CONTRIBUTING.md` of falco (https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#commit-convention) the `new` type (as used in your example) is not mentioned. I'm not familiar with falco, but probably you have some more experience with it and can shed some light on this?

**Comment by leodido** [comment]
>     * the conventional commit specification is not explicit about bumping anything else than `patch`, `feat` or `breaking changes`. Therefore I implemented other types as an "unknown" bump for now. Although many other tools in the field do bump the patch version on any type other than `feat` or `breaking change`. Which way do you prefer for this tool?

Agree, let's stick with only what is mandated by the spec.

>     * in the `CONTRIBUTING.md` of falco (https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#commit-convention) the `new` type (as used in your example) is not mentioned. I'm not familiar with falco, but probably you have some more experience with it and can shed some light on this?

You' right: the "falco" types are not standardized yet. Being one of its authors, I can tell you that `new:` is used to communicate new features in Falco. It's basically a synonym of `feat:` IMHO.

**Comment by juckerf** [comment]
OK, thanks a lot for the clarification.

So, if I got it right the current ruleset should look something like this:
* `patch` bump if `type == "patch"`, regardless of `TypeConfig`
* `minor` bump if `type == "feat"`, regardless of `TypeConfig`
* `minor` bump if `type == "new"`, if `TypeConfig == TypesFalco`
* `major` bump if exclamation mark or `breaking-changes` footer is present, regardless of `TypeConfig`

Altough with this ruleset there's some potential for inconsistency:
* `TypesConventional` bumping "to the letter" (see discussion above about the "unknown" bump https://github.com/leodido/go-conventionalcommits/pull/17#issuecomment-981602231)
* `TypesFalco` bumping "to the letter"
* `TypesMinimal` there's no literal description about bumping for this type, so we stick implicitly to the conventional commit spec - or we try to be consistent across TypeConfigs and return unkown bump for all commits (since nothing/no one mandates the bumps)
* `TypesFreeForm` see `TypesMinimal`

Do you understand my point? And what do you think about it?

**Comment by leodido** [comment]
Hello @juckerf 

I almost forgot this, sorry!

For clarity, let's split the two problems we have here.

The **first** problem is "how to keep track of which types' set the parser is using".

I think we agree on implementing the solution (2) that I proposed above: keep track of which types' set was used with an index.

The **second** problem is "how to bump the version depending on the conventional types (and the types' set they belong to)"

I also see your point about inconsistencies. I believe there will always be inconsistencies in this case, especially for types' set different from the `TypesConventional` one.

So, I think the correct way to do this would be to think of the version bump as a strategy, that depends on two things:

1. which types' set the `ConventionalCommit` instance was created from
2. what exact type prefix (`.Type` field) it contains

I envision that the `func (c *ConventionalCommit) VersionBump() VersionBump {...}` function you wrote should take a **callback that actually implements the version bumping strategy**.

Let's say we have the following declaration:

```go
type VersionBumpStrategy func(*ConventionalCommit) VersionBump
```

Then, we'd have:

```go
func (c *ConventionalCommit) VersionBump(strategy VersionBumpStrategy) VersionBump {
if strategy == nil {
return defaultStrategy(c)
}

return strategy(c)
}
```

This way, we can provide a default opinionated (by us) strategy, which can also contain inconsistencies.

We could even go further and provide different default strategies for the different types' sets we have... Making this mechanism able to support future types' set we may introduce without hassles.

But, more than everything, we provide to the users of this library a way to specify their strategy for bumping the versions.

WDYT? :)

**Comment by juckerf** [comment]
Sorry, I had to find some time to have a look at this.
I like the strategy-approach which gives a lot of flexibility for users and implemented it right away.

**Comment by juckerf** [comment]
@leodido do you have time to have a look at this and perhaps merge this PR if everything is fine with you?

**Comment by juckerf** [comment]
@leodido any update on this?

**Comment by leodido** [comment]
Sorry for leaving this behind (I've been way too busy)...

Taking a look at it rn, thank you!

**Review by leodido — DISMISSED** [review]
LGTM! 🔥

**Review by leodido — APPROVED** [review]

**Comment by juckerf** [comment]
> Sorry for leaving this behind (I've been way too busy)...
> 
> Taking a look at it rn, thank you!

No worries, I can relate :-)
Thanks for the merge!

**Pull request merged**
